LoaderParams:
  numWPTS: 10000
  batch_size: 256
  excludes : ['test','10','25','50','70']
  ParticleNumber: [50,100,150,200]
  norm: True

ValLoaderParams:
  numWPTS: 1000
  batch_size: 256
  excludes : ['200','75','50']
  mode : 'val'

ModelParams:
  in_dims: 3
  out_neurons: 3
  hidden1: 64
  hidden2: 128
  targetLayer: 1

TrainingParams:
  epochs: 100

SinkhornParams:
  temp: [0.001,0.01,0.1,0.2,0.3,0.59,0.6,0.7,0.8,0.9]
  n_iter: 10

deviceNum : 0

#TODO: grid search maybe? optimizerParams:
