LoaderParams:
  numWPTS: 8000
  ParticleNumber: 100
  dims: 3
  norm: True

ModelParams:
  in_dims: 3
  hidden: 128
  numLayers: 2

TrainingParams:
  batch_size: 256
  targetLayer: 0
  epochs: 30
  replace: False
  lr: 1e-3

SinkhornParams:
  temp: 0.59
  n_iter: 10

deviceNum : 0