LoaderParams:
  numWPTS: 8000
  batch_size: 256
  ParticleNumber: 50
  dims: 3
  norm: True

ModelParams:
  in_dims: 3
  hidden1: 128
  hidden2: 256
  targetLayer: 0

distModelParams:
  embedDim: 50

TrainingParams:
  epochs: 100
  replace: False
  lr: 1e-3

SinkhornParams:
  temp: 0.59
  n_iter: 10

deviceNum : 0