LoaderParams:
  numWPTS: 8000
  batch_size: 256
  ParticleNumber: 200
  dims: 3
  norm: False

ValLoaderParams:
  numWPTS: 2000
  batch_size: 256
  norm: False

ModelParams:
  in_dims: 3
  out_neurons: 3
  hidden1: 140
  hidden2: 300
  targetLayer: 1

TrainingParams:
  epochs: 30
  replace: False

SinkhornParams:
  temp: 0.59
  n_iter: 10

deviceNum : 0

#TODO: grid search maybe? optimizerParams:
